/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.TiposUsuarios;
import Controlador.ctrlLogin;
import Controlador.ctrlRegistrarse;
import Modelo.Encrip;
import Modelo.Login;
import Modelo.LoginAdmin;
import Modelo.Registrarse;
import Modelo.SQLConexion;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import Vista.frmLogin;
import Modelo.Registrarse;
import Modelo.SQLConexion;
import java.awt.List;
import java.beans.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author Carlos Burgos
 */
public class frmRegistrarse extends javax.swing.JFrame {

    /*
      Creates new form Registrarse
     */
    public boolean isEmail(String correo) {
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if (mat.find()) {
            return true;
        } else {
            return false;
        }
    }

    public boolean AgregarUsuario() {
        try {
            System.out.println("agregar usuario");
            PreparedStatement addRegistrarse = SQLConexion.getConexion().prepareStatement("insert into tbEmpleados (usuario, correo_electronico, contraseña, idTipoUsuario) values (?,?,?,?)");
            addRegistrarse.setString(1, txtNombreUsuario.getText());
            addRegistrarse.setString(2, txtEmailUsuario.getText());
            addRegistrarse.setString(3, Encrip.convertirSHA256(txtContraseñaUsuario.getText()));
            addRegistrarse.setInt(4, cbTiposUsuarios.getSelectedIndex() + 1);
            addRegistrarse.executeUpdate();
            System.out.println("Se ejecuta el metodo en el modelo");
            return true;
        } catch (SQLException ex) {
            System.out.println("ESTEE ES EL ERRRRROOOOOOOOOOOR"+ex.toString());
            return false;
        }
    }

    public void init() {

        Login modeloLogin = new Login();
        LoginAdmin modeloLoginAdmin = new LoginAdmin();
        Registrarse modeloRegistrarse = new Registrarse(); // Crea una instancia del modelo Registrarse
        frmRegistrarse vistaRegistrarse = new frmRegistrarse();  // Crea una instancia de la vista frmRegistrarse
         // Crea una instancia del controlador para el formulario de login
        ctrlRegistrarse controladorRegistrarse = new ctrlRegistrarse(modeloRegistrarse, vistaRegistrarse); // Crea una instancia del controlador para el formulario de registro
        

        Registrarse regist = new Registrarse();
        frmRegistrarse vista = new frmRegistrarse();

        //ctrlRegistrarse regis = new ctrlRegistrarse(regist , vista);
        System.out.println("Este es el metodo init");
        System.out.println("metodo init registrarse");

        vista.setVisible(true);

    }

    public frmRegistrarse() {
        System.out.println("Tipo usuario");
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(txtFondo, "src/Imagenes/fondo_interfaces.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(txtLogo, "src/Imagenes/logo.png");

        cbTiposUsuarios.removeAllItems();
        var tiposUsuarios = new ArrayList<TiposUsuarios>();
        ResultSet rs = null;

        try {
            java.sql.Statement statement = SQLConexion.getConexion().createStatement();

            String query = "SELECT * FROM tbTipoUsuarios";

            rs = statement.executeQuery(query);

            while (rs.next()) {
                TiposUsuarios nuevoItem = new TiposUsuarios(rs.getInt("idTipoUsuario"), rs.getString("nombre_tipoUsuario"));
                tiposUsuarios.add(nuevoItem);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        for (TiposUsuarios item : tiposUsuarios) {
            cbTiposUsuarios.addItem(item.getTipoUsuario());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmailUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtLogin = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        txtFondo = new javax.swing.JLabel();
        txtContraseñaUsuario = new javax.swing.JPasswordField();
        cbTiposUsuarios = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("Nombre de Usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 250, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("Email:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        txtEmailUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        txtEmailUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailUsuarioFocusLost(evt);
            }
        });
        txtEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 250, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Tipo Usuario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        btnRegistrarse.setBackground(new java.awt.Color(153, 204, 0));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseEntered(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 150, 70));

        txtLogin.setForeground(new java.awt.Color(102, 153, 255));
        txtLogin.setText("¿Ya tienes una cuenta?");
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginMouseClicked(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));
        jPanel1.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 230, 230));
        jPanel1.add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 360, 610));

        txtContraseñaUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jPanel1.add(txtContraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 250, 40));

        cbTiposUsuarios.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        cbTiposUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbTiposUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("Contraseña:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        if (txtContraseñaUsuario.getText().isEmpty() || txtEmailUsuario.getText().isEmpty() || txtNombreUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos");
        } else {
            AgregarUsuario();
               Vista.frmLogin login = new Vista.frmLogin();
                login.InitLogin();
                 dispose();
            
            JOptionPane.showMessageDialog(null, "El usuario ha sido registrado");
            
          
            
        }


      
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void txtLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseClicked
        Vista.frmLogin login = new Vista.frmLogin();
        login.InitLogin();
        dispose();
    }//GEN-LAST:event_txtLoginMouseClicked

    private void btnRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarseMouseEntered

    private void txtEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUsuarioActionPerformed

    }//GEN-LAST:event_txtEmailUsuarioActionPerformed

    private void txtEmailUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailUsuarioFocusGained

    }//GEN-LAST:event_txtEmailUsuarioFocusGained

    private void txtEmailUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailUsuarioFocusLost
        if (!isEmail(txtEmailUsuario.getText())) {
            JOptionPane.showMessageDialog(null, "Ingresa un correo valido", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            txtEmailUsuario.requestFocus();
        }

    }//GEN-LAST:event_txtEmailUsuarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // Resto del código

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> cbTiposUsuarios;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField txtContraseñaUsuario;
    public javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JLabel txtFondo;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtLogo;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
