/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author deleo
 */
public class Inicio extends javax.swing.JFrame {

    
    public Inicio() {
        initComponents();
        
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabela1,"src/Imagenes/calendario.png");
          rsscalelabel.RSScaleLabel.setScaleLabel(jLabel4,"src/Imagenes/logo_exportaciones.png");
                    rsscalelabel.RSScaleLabel.setScaleLabel(jLabela1,"src/Imagenes/elemento1.png");
                              rsscalelabel.RSScaleLabel.setScaleLabel(jLabel3,"src/Imagenes/logo OIRSA.png");
                                        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2,"src/Imagenes/icono_usuario.png");
          rsscalelabel.RSScaleLabel.setScaleLabel(jLabel6,"src/Imagenes/logo_productos.png");
                    rsscalelabel.RSScaleLabel.setScaleLabel(jLabel5,"src/Imagenes/logo_organizacion.png");




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnExportaciones = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnInventario1 = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnOrganizacion = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        jLabela1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo OIRSA.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("Bienvenido");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_usuario.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -90, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_inventario.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_exportaciones.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 180, 90));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("Exportaciones");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_productos.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 180, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/organizacion.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 200, 120));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 180, 110));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("Inventario");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        btnExportaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnExportaciones.setBorder(null);
        btnExportaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 190, 150));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("Productos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        btnInventario1.setBackground(new java.awt.Color(255, 255, 255));
        btnInventario1.setBorder(null);
        btnInventario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventario1MouseClicked(evt);
            }
        });
        btnInventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventario1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 150));

        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setBorder(null);
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosMouseClicked(evt);
            }
        });
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 180, 160));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("Organización");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setText("Calendario de Actividades");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 170, -1));

        btnOrganizacion.setBackground(new java.awt.Color(255, 255, 255));
        btnOrganizacion.setBorder(null);
        btnOrganizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrganizacionMouseClicked(evt);
            }
        });
        jPanel1.add(btnOrganizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 180, 160));

        btnActividades.setBackground(new java.awt.Color(255, 255, 255));
        btnActividades.setBorder(null);
        btnActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadesActionPerformed(evt);
            }
        });
        jPanel1.add(btnActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 180, 160));

        jLabela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/elemento1.png"))); // NOI18N
        jPanel1.add(jLabela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportacionesActionPerformed
        frmExportaciones exp = new frmExportaciones();
       exp.setVisible(true);
    }//GEN-LAST:event_btnExportacionesActionPerformed

    private void btnInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventario1ActionPerformed
        frmInventario inv = new frmInventario();
        
       inv.setVisible(true);
    }//GEN-LAST:event_btnInventario1ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        frmProductos pro = new frmProductos();
        pro.Init();
       // pro.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesActionPerformed
       calendarioACT Cal = new calendarioACT();
        Cal.setVisible(true);
    }//GEN-LAST:event_btnActividadesActionPerformed

    private void btnProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseClicked
           
    }//GEN-LAST:event_btnProductosMouseClicked

    private void btnInventario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventario1MouseClicked
       
    }//GEN-LAST:event_btnInventario1MouseClicked

    private void btnOrganizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrganizacionMouseClicked
        Organizacion org = new Organizacion();
       org.setVisible(true);
    }//GEN-LAST:event_btnOrganizacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnExportaciones;
    private javax.swing.JButton btnInventario1;
    private javax.swing.JButton btnOrganizacion;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabela1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
